# Generated by Django 3.2.22 on 2023-10-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titel',
            new_name='title',
        ),
    ]
